POST  http://localhost:3000/login
content-type: application/json

{
	"username": "tom",
	"password": "tom1"
}


###
POST  http://localhost:3000/logout


###
POST https://recipe-tom-almog.herokuapp.com/register
content-type: application/json

{
	"username": "trypost",
	"password": "trypost"
}


###
GET https://recipe-tom-almog.herokuapp.com/recipes/random


###
GET http://localhost:3000/search?query=cheese&number=4


###
GET http://localhost:3000/recipes/information?recipe_id=632075

###
GET http://localhost:3000/recipes/preparingRecipe/638552

###
GET http://localhost:3000/profile/watchedRecipes

###

GET http://localhost:3000/profile/favoriteRecipes

###
GET http://localhost:3000/profile/recipeInfo/4771103b-eeb9-4569-b40a-a88b6dcfca05

###
GET https://recipe-tom-almog.herokuapp.com/familyRecipes


###
GET https://recipe-tom-almog.herokuapp.com/profile/personalRecipes


###
GET https://recipe-tom-almog.herokuapp.com/profile/familyRecipes/651e24b6-8386-449b-91f9-e474d5966b57

###

GET https://recipe-tom-almog.herokuapp.com/profile/familyRecipes
###

GET http://localhost:3000/profile/personalRecipes

###
POST  http://localhost:3000/profile/familyRecipes
content-type: application/json

{
"title":"Persian - Tohme Sharbati",
"image_URL":"",
"readyInMinutes":"7",
"aggregateLikes":0,
"vegan":1,
"vegetarian": 1,
"gluttenFree":1,
  "ingredients": [
    {"Sesame(Glazing and decoration)": 1 },
	{"Cups Water": 5},
	{"Cup Rose water": 0.25},
	{"Tablespoons Sugar ": 4},
    {"Tablespoon Flax seeds ": 1}
    ],
"instructions": "(1)Put everything in a bowl, stir for about 5 minutes.(2)Add ice then drink after fasting.",
"servings":6,
"type": "family",
"recipeOwner": "Yafa Golan(Grandmother)",
"inEvent": "Every Yom Kippur"
}